name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Intro JS
      id: intro-js
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Intro JS
        setup-command: npm install
        command: npm run test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INTRO-JS_RESULTS: "${{steps.intro-js.outputs.result}}"
      with:
        runners: intro-js
